version: '3.8'
services:
  app:
    build:
      context: .
      target: dev
    image:  todo:development
    volumes:
      - .:/app
    ports:
      - 3000:3000
    env_file:
      - .env
    network_mode: bridge
    depends_on:
      - postgres


  postgres:
    container_name: postgres
    image: postgres:15
    volumes:
      - pg-dev-data:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=$DB_USERNAME
      - POSTGRES_DB=$DB_NAME
      - POSTGRES_PASSWORD=$DB_PASSWORD
      - POSTGRES_HOST=localhost

volumes:
  pg-dev-data:
    driver: local